### ISSUE TITLE
Release 2.1.2

### ISSUE THREAD

**Issue by avoinea** [collective/collective.taxonomy#122]
Can we release 2.1.2, as 2.1.1 doesn't work anymore with Plone 6:

```
Traceback (most recent call last):
  File "/app/bin/zconsole", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/Zope2/utilities/zconsole.py", line 50, in main
    runscript(namespace.zopeconf, *namespace.scriptargs)
  File "/app/lib/python3.9/site-packages/Zope2/utilities/zconsole.py", line 13, in runscript
    make_wsgi_app({}, zopeconf)
  File "/app/lib/python3.9/site-packages/Zope2/Startup/run.py", line 61, in make_wsgi_app
    starter.prepare()
  File "/app/lib/python3.9/site-packages/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/app/lib/python3.9/site-packages/Zope2/Startup/starter.py", line 94, in startZope
    Zope2.startup_wsgi()
  File "/app/lib/python3.9/site-packages/Zope2/__init__.py", line 36, in startup_wsgi
    _startup()
  File "/app/lib/python3.9/site-packages/Zope2/App/startup.py", line 126, in startup
    load_zcml()
  File "/app/lib/python3.9/site-packages/Zope2/App/startup.py", line 41, in load_zcml
    load_site()
  File "/app/lib/python3.9/site-packages/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/src/python/Modules/pyexpat.c", line 461, in EndElement
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/app/lib/python3.9/site-packages/OFS/metaconfigure.py", line 47, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/src/python/Modules/pyexpat.c", line 461, in EndElement
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/app/lib/python3.9/site-packages/plone/autoinclude/zcml.py", line 39, in includePluginsDirective
    loader.load_configure(context, filename, dists)
  File "/app/lib/python3.9/site-packages/plone/autoinclude/loader.py", line 148, in load_configure
    load_zcml_file(context, module_name, package, filename)
  File "/app/lib/python3.9/site-packages/plone/autoinclude/loader.py", line 141, in load_zcml_file
    include(context, filename, package)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/src/python/Modules/pyexpat.c", line 461, in EndElement
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/src/python/Modules/pyexpat.c", line 407, in StartElement
  File "/usr/local/lib/python3.9/xml/sax/expatreader.py", line 369, in start_element_ns
    self._cont_handler.startElementNS(pair, None,
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 268, in startElementNS
    self._handle_exception(ex, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 235, in _handle_exception
    reraise(exc, None, sys.exc_info()[2])
  File "/app/lib/python3.9/site-packages/zope/configuration/_compat.py", line 30, in reraise
    raise value.with_traceback(tb)
  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 266, in startElementNS
    self.context.begin(name, data, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 701, in begin
    self.stack.append(self.stack[-1].contained(__name, __data, __info))
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 1071, in contained
    return RootStackItem.contained(self, name, data, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 895, in contained
    adapter = factory(self.context, data, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 1508, in factory
    return ComplexStackItem(self, context, data, info)
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 1225, in __init__
    args = toargs(newcontext, meta.schema, data)
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 1687, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/app/lib/python3.9/site-packages/zope/configuration/fields.py", line 172, in fromUnicode
    value = self.context.resolve(name)
  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 226, in resolve
    __import__(mname)
  File "/app/lib/python3.9/site-packages/collective/taxonomy/exportimport.py", line 4, in <module>
    from collective.taxonomy.factory import registerTaxonomy
  File "/app/lib/python3.9/site-packages/collective/taxonomy/factory.py", line 8, in <module>
    from collective.taxonomy.utility import Taxonomy
  File "/app/lib/python3.9/site-packages/collective/taxonomy/utility.py", line 12, in <module>
    from collective.taxonomy import generated
  File "/app/lib/python3.9/site-packages/collective/taxonomy/generated.py", line 11, in <module>
    from plone.synchronize import synchronized
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/app/lib/python3.9/site-packages/collective/taxonomy/configure.zcml", line 34.2
    File "/app/etc/site.zcml", line 14.2-14.23
    File "/app/lib/python3.9/site-packages/Products/CMFPlone/configure.zcml", line 102.2-106.8
    File "/app/lib/python3.9/site-packages/eea/kitkat/configure.zcml", line 8.2-8.43
    ModuleNotFoundError: No module named 'plone.synchronize'
```

**Comment by petschki** [comment]
I've released a new 2.2.0 version ... 2.2.x should be used for Plone6/py3 only ... we can now start cleaning up.
